# Generated by Django 4.1.3 on 2022-11-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.TextField(max_length=80),
        ),
    ]
